// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgSXHmofblGOiPV3b1vT2-I_rmaNaOlTw',
    appId: '1:254565017038:web:fb2dd881cab2a15887f79f',
    messagingSenderId: '254565017038',
    projectId: 'andro-b0e02',
    authDomain: 'andro-b0e02.firebaseapp.com',
    storageBucket: 'andro-b0e02.appspot.com',
    measurementId: 'G-4K0KBT28NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJC0LYAvFvqC5vd7Gwo800bkIqBB4YC4',
    appId: '1:254565017038:android:45db9beaa1ce12e887f79f',
    messagingSenderId: '254565017038',
    projectId: 'andro-b0e02',
    storageBucket: 'andro-b0e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SojtmYSj37RICxtCD0KG3eIHokmqaY8',
    appId: '1:254565017038:ios:9aa42d8a1b2ef2ad87f79f',
    messagingSenderId: '254565017038',
    projectId: 'andro-b0e02',
    storageBucket: 'andro-b0e02.appspot.com',
    iosBundleId: 'com.example.eipscanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-SojtmYSj37RICxtCD0KG3eIHokmqaY8',
    appId: '1:254565017038:ios:fa29e60a2599701a87f79f',
    messagingSenderId: '254565017038',
    projectId: 'andro-b0e02',
    storageBucket: 'andro-b0e02.appspot.com',
    iosBundleId: 'com.example.eipscanApp.RunnerTests',
  );
}
